### ISSUE TITLE
Compressing in browser preupload

### ISSUE THREAD

**Issue by Charuru** [google/brunsli#67]
Can we have some instructions on how to setup wasm to do this please?

**Comment by eustas** [comment]
Hello. You could check https://brusnli.dev/test.html
On this page ServiceWorker upgrades the HTTP request so that nginx plugin sends compressed file instead of original. When response arrives, ServiceWorker decodes it and passes as JPEG to browser.

Using up WASM is usually simple:

 - follow the Emscripten [instructions](https://emscripten.org/docs/getting_started/downloads.html)
 - set `CC` and `CXX` environment variables to point to `emcc` and `em++`
 - freshly configure and build with CMake

Please refine the question, if I got it wrong.

**Comment by Charuru** [comment]
Thanks, the question was about how to upload a compressed file with image data from canvas instead of compressing on the server.

**Comment by eustas** [comment]
With current API it could be done in 2 steps:

* `canvas.toDataURL('image/jpeg', quality / 100.0);`, then decode base64 payload to bytes
* pass bytes to Brunsli, like here: https://github.com/google/brunsli/blob/master/docs/index.html#L231
